<?php

namespace App\Http\Controllers\Backend;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Models\workspaces_model;


/* ******************************************************
    This file is generated by SNOOBIX on Jun 01, 2024
    Please visit snoobix.com for more details
****************************************************** */


class Workspaces extends Controller
{
    public function __construct()
    {
        //if (!Auth::check()) return 'access_denied';
    }
   
    public function index()
    { 
        $data['module_title'] = 'Workspaces';
		$data['rows'] = workspaces_model::orderBy('id', 'desc')->get();
		return view("backend/workspaces_list", $data);
	
    }


    public function create()
    {
        $data['module_title'] = 'Workspaces';
       //$data['row'] = [];
       $data['submit_path'] = 'store';
       $data['module_name'] = 'Workspaces';
       return view("backend/workspaces_addedit", $data);       
    }

   
    public function store(Request $request)
    {
         $data['module_title'] = 'Workspaces';
        /* $request->validate([
            [[validateFieldsArray]]
        ]); */

        /* $record = [
			[[fieldsArray]]
		];
		$iscreated = workspaces_model::create($record); */

        $record = $request->all();
        if ($request->hasFile('logo')) {
            $imgFile = $request->file('logo')->store('public');
            $record['logo'] = $imgFile;
        }
        $record['member_ids'] = implode(',',$request->post('member_ids'));

        
        $savedid = workspaces_model::create($record)->id;
		if($savedid){
			 //return view("backend/workspaces_addedit")->with('flash_success', "Record is saved successfuly");
             return redirect('backend/workspaces/create')->with('flash_success', "Record is saved successfuly");
		}else{
			$data['row'] = $request->all();
			return view("backend/workspaces_addedit", $data)->with('flash_failure', "Record is NOT saved successfuly");
		}
    }

    
    public function show()
    {
        //
    }

    
    public function edit($id)
    {
         $data['module_title'] = 'Workspaces';
        $data['submit_path'] = 'update';
        $recCond = [
			'id' => str2id($id)
		];
		$data['row'] = workspaces_model::where($recCond)->first();
		return view("backend/workspaces_addedit", $data);
    }

   
    public function update(Request $request)
    {
		 $data['module_title'] = 'Workspaces';
        $id = $request->post('id');
        $id = str2id($id);
        $vworkspaces_model = workspaces_model::find($id);
        
         $record = $request->all();
         if ($request->hasFile('logo')) {
$imgFile = $request->file('logo')->store('public');
$record['logo'] = $imgFile;
}

        
        $isaved = $vworkspaces_model->fill($record)->save();  //this will save record with all fillable items

        if($isaved){
			//return view("backend/workspaces_addedit")->with('flash_success', "Record is updated successfuly");
            return redirect('backend/workspaces')->with('flash_success', "Record is updated successfuly");
		}else{

			//$data['postData'] = $record;
             $data['submit_path'] = 'update';
             $recCond = [
                'id' => $id,
            ];
            $data['row'] = workspaces_model::where($recCond)->first();
			return view("backend/workspaces_addedit", $data)->with('flash_failure', "Record is NOT updated successfuly");
		}		
    }

   
    public function destroy(Request $request)
    {
        $id = $request->post('delid');
        $id = str2id($id);
        $vworkspaces_model = workspaces_model::find($id);
        $isdeleted = $vworkspaces_model->delete();
        if($isdeleted ){
            return redirect()->route('backend.workspaces')->with('flash_success','Record is deleted successfuly');
        }else{
            return redirect()->route('backend.workspaces')->with('flash_failure','Record is not deleted, try again later');
        }
    }
}
