@extends('layouts.app')
@section('content')

        {{-- ************************************************
         This file is generated by SNOOBIX on Jun 01, 2024
         Please visit snoobix.com for more details
         *********************************************** --}}

    <div class="page-content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <form action="{{route('backend.users.'.$submit_path)}}" method="POST" ENCTYPE="multipart/form-data">
                        @csrf
                        <div class="card-header">
                            <div class="row" >
                                <div class="col-3 text-start">
                                    <div class="page-title-box d-flex align-items-center justify-content-between">
                                        <h4 class="card-title">{{ucwords($module_title)}} </h4>
                                    </div>
                                </div>
                                <div class="col-6 text-center">
                                    @if(session('flash_success') != '')
                                        <div class="alert alert-success">{{session('flash_success')}}</div>
                                    @endif
                                    @if(session('flash_failure') != '')
                                        <div class="alert alert-danger">{{session('flash_failure')}}</div>
                                    @endif
                                </div>
                                <div class="col-3 text-end">
                                    <a href="{{route('backend.users')}}" class="btn btn-info btn-md"  >List Page</a>
                                </div> 
                            </div>
                        </div>
                        <div class="card-body">
                            
                            <div class="row">
                                <div class="col-lg-12">
                                
                                        
                                            <div class="row"> 

                                                    
		<input
			type="hidden"
			id="id"
			name="id"
			value="@if(isset($row->id)) {{ $row->id }} @endif"
		/>
		




<div class="col-md-6 mt-3">
	<div class="form-group">
		<label class="form-label" for="name">NAME</label>
		<input
			type="text"
			id="name"
			name="name"
			class="form-control"
			value="@if(isset($row->name)){{$row->name}}@endif"
			required
		/>
	</div>
	<div id="diverr_name" text-danger></div>
</div>



<div class="col-md-6 mt-3">
	<div class="form-group">
        <label for='email'>EMAIL</label>
        <input
            type="email"
            id="email"
            name="email"
            class="form-control"
            value="@if(isset($row->email)) {{ $row->email }} @endif"
            required>
    </div>
	
    <div id="diverr_email" text-danger></div>
</div>


<div class="col-md-6 mt-3">
		<div class="form-group">
		<label class="form-label" for="email_verified_at">EMAIL VERIFIED AT</label>
		<input
			type="datetime"
			id="email_verified_at"
			name="email_verified_at"
			class="form-control"
			value="@if(isset($row->email_verified_at)) {{ $row->email_verified_at }} @endif"
			
		/>
		
	</div>
	<div id="diverr_email_verified_at" text-danger></div>
</div>



<div class="col-md-6 mt-3">
	<div class="form-group">
		<label class="form-label" for="password">PASSWORD</label>
		<input
			type="password"
			id="password"
			name="password"
			class="form-control"
			
			value="@if(isset($row->password)) {{ $row->password }} @endif"
			required
		>
		
	</div>
	<div id="diverr_password" text-danger></div>
</div>



		<input
			type="hidden"
			id="remember_token"
			name="remember_token"
			value="@if(isset($row->remember_token)) {{ $row->remember_token }} @endif"
		/>
		



<div class="col-md-6 mt-3">
	<div class="form-group">
    <label class="form-label" for="account_type">ACCOUNT TYPE</label>
@php    
    if(!Empty($row)){ 
        $selected = $row->account_type; 
    }else{
        $selected = '';
    }
    $options = explode(',','Admin,User');
 @endphp

		 <select class="form-control" name="account_type" id="account_type"> 
		   <option value="">--Select--</option>
		   @foreach ($options as $option)
			<option value="{{$option}}" {{($option == $selected) ? 'selected' : '' }}> 
				{{$option}} 
			</option>
		  @endforeach    
		</select>

 </div>
 <div id="diverr_account_type" text-danger></div>
</div>


<div class="col-md-6 mt-3">
	<div class="form-group">
    <label class="form-label" for="active">ACTIVE</label>

@php
    
    if(!Empty($row)){ 
        $selected = $row->active; 
    }else{
        $selected = '';
    }
    $options = get_list_values('active_status','is_active');
    //pre($options);
	//$options = $active;
 @endphp

		 <select class="form-control" name="active" id="active"> 
		   <option value="">--Select--</option>
		   @foreach ($options as $key => $value)
			<option value="{{$key}}" {{($key == $selected) ? 'selected' : '' }}> 
				{{$value}} 
			</option>
		  @endforeach    
		</select>

 </div>
 <div id="diverr_active" text-danger></div>
</div>
		




                                                
                                            </div>
                                            
                                            <input type="hidden" name="continue" id="continue" value="Y" />
                                            <input type="hidden" name="id" id="id" value="@if(isset($row->id)) {{id2str($row->id)}} @endif" />
                                            
                                </div>
                            </div>
                        </div>

                        <div class="card-footer">
                            <div class="row " > 
                                <div class="col-md-6 text-start mt-2">
                                    <button type="submit" class="btn btn-primary waves-effect waves-light w-md">Submit</button>
                                </div>
                                <div class="col-md-6 text-end  mt-2">
                                    <button type="reset" class="btn btn-outline-danger waves-effect waves-light w-md">Reset</button>
                                </div>
                            </div>
                        </div>
                        </form>
                    </div>
                </div>
            </div>

        </div> 
    </div>


@endsection